name: Release

on: push

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable

    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/list-nonascii
        asset_name: ubuntu-list-nonascii
        tag: ${{ github.event.ref }}
      
  release-windows:
    runs-on: windows-latest

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable

    - uses: actions/checkout@v1

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/list-nonascii.exe
        asset_name: windows-list-nonascii.exe
        tag: ${{ github.event.ref }}
  
  release-macos:
    runs-on: macos-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/list-nonascii
        asset_name: macos-list-nonascii
        tag: ${{ github.event.ref }}
